
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatPhoto", targetNamespace = "http://service/", className = "client.GetCatPhoto")
    @ResponseWrapper(localName = "getCatPhotoResponse", targetNamespace = "http://service/", className = "client.GetCatPhotoResponse")
    @Action(input = "http://service/PersonWebService/getCatPhotoRequest", output = "http://service/PersonWebService/getCatPhotoResponse")
    public byte[] getCatPhoto();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://service/", className = "client.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://service/", className = "client.GetPersonsResponse")
    @Action(input = "http://service/PersonWebService/getPersonsRequest", output = "http://service/PersonWebService/getPersonsResponse")
    public List<Person> getPersons(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws PersonServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://service/", className = "client.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://service/", className = "client.DeletePersonResponse")
    @Action(input = "http://service/PersonWebService/deletePersonRequest", output = "http://service/PersonWebService/deletePersonResponse", fault = {
        @FaultAction(className = PersonServiceException_Exception.class, value = "http://service/PersonWebService/deletePerson/Fault/PersonServiceException")
    })
    public int deletePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws PersonServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws PersonServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://service/", className = "client.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://service/", className = "client.UpdatePersonResponse")
    @Action(input = "http://service/PersonWebService/updatePersonRequest", output = "http://service/PersonWebService/updatePersonResponse", fault = {
        @FaultAction(className = PersonServiceException_Exception.class, value = "http://service/PersonWebService/updatePerson/Fault/PersonServiceException")
    })
    public int updatePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonRequest arg0)
        throws PersonServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws PersonServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://service/", className = "client.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://service/", className = "client.CreatePersonResponse")
    @Action(input = "http://service/PersonWebService/createPersonRequest", output = "http://service/PersonWebService/createPersonResponse", fault = {
        @FaultAction(className = PersonServiceException_Exception.class, value = "http://service/PersonWebService/createPerson/Fault/PersonServiceException")
    })
    public int createPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonRequest arg0)
        throws PersonServiceException_Exception
    ;

}
