
package client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PersonServiceException", targetNamespace = "http://service/")
public class PersonServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PersonServiceException_Exception(String message, PersonServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PersonServiceException_Exception(String message, PersonServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.PersonServiceException
     */
    public PersonServiceException getFaultInfo() {
        return faultInfo;
    }

}
