
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://service/", className = "client.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://service/", className = "client.DeletePersonResponse")
    @Action(input = "http://service/PersonWebService/deletePersonRequest", output = "http://service/PersonWebService/deletePersonResponse")
    public int deletePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://service/", className = "client.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://service/", className = "client.UpdatePersonResponse")
    @Action(input = "http://service/PersonWebService/updatePersonRequest", output = "http://service/PersonWebService/updatePersonResponse")
    public int updatePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://service/", className = "client.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://service/", className = "client.CreatePersonResponse")
    @Action(input = "http://service/PersonWebService/createPersonRequest", output = "http://service/PersonWebService/createPersonResponse")
    public int createPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://service/", className = "client.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://service/", className = "client.GetPersonsResponse")
    @Action(input = "http://service/PersonWebService/getPersonsRequest", output = "http://service/PersonWebService/getPersonsResponse")
    public List<Person> getPersons(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonRequest arg0);

}
