
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://service/", className = "client.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://service/", className = "client.GetPersonsResponse")
    @Action(input = "http://service/PersonWebService/getPersonsRequest", output = "http://service/PersonWebService/getPersonsResponse")
    public List<Person> getPersons(
        @WebParam(name = "arg0", targetNamespace = "")
        FindPersonRequest arg0);

}
